### ISSUE TITLE
site-print doesn't work with plugin

### ISSUE THREAD

**Issue by Q-efx** [MikhailKravets/mkdocs_puml#25]
**Describe the bug**
If you create a single page via site-print plugin, you get no images but UID reference numbers.

**To Reproduce**
install this plugin
install site-rpint
Create simple plantuml diagram
Create single page html

**Expected behavior**
Diagrams are also in the single page html

**Comment by MikhailKravets** [comment]
Hi @Q-efx, are you talking about [mkdocs-print-site-plugin](https://github.com/timvink/mkdocs-print-site-plugin/) plugin?

**Comment by MikhailKravets** [comment]
Hey @Q-efx, are there any updates on the issue?

**Comment by rbejar** [comment]
Hi. I am having the same issue. Using mkdocs-print-site-plugin==2.3.5 and mkdocs-puml==1.2.0. I see the UUIDs, but not the UML diagramas when I go to the print_page of my site. If there is anything I can do to help, please, tell me.

**Comment by rbejar** [comment]
Hi. We have worked around this by using another plugin (plantuml-markdown==3.9.1). You just need to add it to the markdown_extensions section of the mkdocs.yml file and in the code blocks instead of ```puml you write ```plantuml. And that's essentially it. In any case, thanks for your work with mkdocs-puml.

**Comment by MikhailKravets** [comment]
This issue requires thorough investigation of `mkdocs-print-site-plugin` to work out the solution. I bet we have operlaping events.

@rbejar , `plantuml-markdown` makes 1 request to puml server per 1 diagram. `mkdocs-puml`, on the contrary, use multithreading to make requests to the server. So, if you have many diagrams `mkdocs-puml` works way faster.

**Comment by MikhailKravets** [comment]
@Q-efx, @rbejar, I've figured out the problem. Appeared that I've returned correct value from `on_post_page` event but mkdocs doesn't apply the `output` to `Page` object. I had to do it manually. And `mkdocs-print-site-plugin`, on the contrary, works with `Page` objects.

I plan to publish a new version with this fix over few days 🎉

**Comment by MikhailKravets** [comment]
The issue was fixed in #27. Please upgrade mkdocs-puml package to the newest `1.2.1` version.

**Comment by watermarkhu** [comment]
This seems to be an issue (again) with `mkdocs-puml==2.3.0` and `mkdocs-print-site-plugin==2.8`

**Comment by MikhailKravets** [comment]
@watermarkhu, I reopen the issue for further research
