### ISSUE TITLE
PlantUML.js support

### ISSUE THREAD

**Issue by yarons** [MikhailKravets/mkdocs_puml#34]
**Is your feature request related to a problem? Please describe.**
I had to develop a whole GitHub Actions workflow to deal with puml conversion to SVG in order to display diagrams as part of my documentation.

**Describe the solution you'd like**
Adding a PlantUML.js support, thus eliminating the need for pre-processing and Java.

**Describe alternatives you've considered**
I developed a GitHub Actions workflow to start a Java application to convert all the puml parts to SVG and then add them to the MkDocs generated HTML as an `<img>`.

**Additional context**
This is an example of this native JS implementation:
https://plantuml.github.io/plantuml.js

**Comment by MikhailKravets** [comment]
Thank you for this suggestion @yarons! I didn't know that PlantUML is available through WASM. If we have this integrated to the package it can potentially solve #33.

**Comment by yarons** [comment]
Oh no, thank you for all your awesome work! Hoping to use this Dark/Light theme implementation soon, I also need it :)

**Comment by MikhailKravets** [comment]
Hi @yarons, since version 2.0.0 `mkdocs_puml` has caching functionality that also allows you to build diagrams and commit them to git. As for myself I'm not sure yet if it's 100% true approach to do so but it will allow you to use pre-built diagrams in github actions. Read more at [Setup Caching](https://mikhailkravets.github.io/mkdocs_puml/getting_started/setup/#cache) section of the documentation.

Please @yarons, confirm if this approach works for you?

**Comment by yarons** [comment]
I'm not sure it's the right approach for me, the aforementioned project was neglected so I'll need to find another way to test this functionality, thank you :)

**Comment by MikhailKravets** [comment]
Thanks for your response @yarons! I'm not sure that it's a good idea to implement support for plantuml.js right now; it will take a lot of time and I'm not sure if I'm even able to do it 😅. I suppose having current approach with web-server is versatile enough. So, I'm going to close this issue. Let me know if you have issues or suggestions. Thanks!

**Comment by yarons** [comment]
@MikhailKravets it's becoming a little more complicated when considering CI pipelines, running PlanUML as a CLI binary is also a good solution.
