### ISSUE TITLE
preserveAspectRatio is incorrect and not configurable

### ISSUE THREAD

**Issue by dev-artisan** [MikhailKravets/mkdocs_puml#43]
**Describe the bug**
When using [mkdocs-exporter](https://github.com/adrienbrignon/mkdocs-exporter) plugin to export to PDF, the process errors during PDF creation saying:
```
preserveAspectRatio has invalid value "true"
```

**To Reproduce**
1. Install the [mkdocs-exporter](https://github.com/adrienbrignon/mkdocs-exporter)
2. Export a page to PDF that has a puml diagram
3. Check logs

**Expected behavior**
The error should not appear and the preserveAspectRatio attribute of the svg should be configurable using the `skinparam` option provided by plantuml e.g.
```
@startuml
skinparam preserveAspectRatio xMinYMid slice
@enduml
```

See valid options for attribute [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio).

**Additional context**
The issue seems to be a hard override here:
https://github.com/MikhailKravets/mkdocs_puml/blob/master/mkdocs_puml/puml.py#L126C27-L126C46

**Comment by dev-artisan** [comment]
**Suggestion:**
Perhaps just remove the line that is forcing it to "true"

**Comment by MikhailKravets** [comment]
Hi @dev-artisan, thanks for raising this issue!

If we remove a `preserveAspectRatio` propetry from SVG, diagrams will not be correctly displayed in web-site (by default). Perhaps, it'll be better to  embed an aspect ratio settings in `puml` itself. I'll research this problem a bit more.

**Comment by dev-artisan** [comment]
Suggested solution in the below pull request:

https://github.com/MikhailKravets/mkdocs_puml/pull/45
