### ISSUE TITLE
num_workers removed

### ISSUE THREAD

**Issue by cjander** [MikhailKravets/mkdocs_puml#66]
**Is your feature request related to a problem? Please describe.**
Our default configs are setting "num_workers" explicitly, our build is now failing since apparently num_workers was removed with release 2.0.0, just noticed that when checking your pr for 2.0.0. there is no hint about that in the release notes any hint when removing such thing would be highly appreciated.

**Comment by MikhailKravets** [comment]
Hi @cjander. It was removed, indeed. It's not needed anymore such as now `mkdocs_puml` performs all requests asynchronously. With the release of version 2.0.0, the library has grown significantly. You're right—it's time not only to include such features in the release, but also to establish a more organized release policy.

Have you managed to solve your problem, or do you need help with it?

**Comment by cjander** [comment]
I solved it by removing the line, so all good. I mainly opened the issue for others who may face similar issues now (num_workers was in your examples, so i assume plenty of others may have the issue as well)
