### ISSUE TITLE
Syntax error for digraph with included theme

### ISSUE THREAD

**Issue by cre8** [MikhailKravets/mkdocs_puml#87]
**Describe the bug**

**To Reproduce**

Visit: https://www.plantuml.com/plantuml/uml/ZL9DQyCm3BtdLtWzjT3Kzq576RsiPL3Oe8SnWXEhYObZ6rjEAQF_VOwTbdKVC5yiFRqdFHcl73ABlfFPdL2Lz1n8WsZSFQMM7HUrmCQNte6jj49GkAXqHvz5sp0XjvRrW8vsBTULAqpeGZlc42p51ZfmbCE1UOcKCzikXdh6HMsPQSY6V6GP8SwNAG-Z1s5X12-CrRtWO0E5XEFm965v4582Zq2bfRPBAUe6I-aXOfAL89UJtTEQx4Rv91QC8MzZiOLJ7jAfCM64wETa27mvcxn7vh1bmHcogm12jm68XFElVeyisC9_EAqjWFfgTH-LoQJIgeA2UIuW1DVv4PwJ2pxwvD3Vh1Ho4KJJT0yRpSab3clEHlVnAVA76xaJjIBJbtM-sRycNkByV8hlp2pv2Dm_l2V1zl4YE6ShK3nyWKy=

With this input:
```
@startuml
!include https://raw.githubusercontent.com/MikhailKravets/mkdocs_puml/master/themes/default/dark.puml
digraph J {

  subgraph cluster_pid_provider {
    style=filled
    color=lightblue
    label="PID Provider"
    pp [label="key-pp (pp_priv, pp_pub)"]
    user_data [label="eID data"]
  }

  subgraph cluster_wallet {
    style=filled
    color=lightgreen
    label="Wallet"
    nonce_audience [label="nonce, audience"]
    dev [label="key-device (device_pub, device_priv)"]
  }
  pp -> dev [label="sign (SD-JWT)"]
  pp -> user_data [label="sign (SD-JWT)"]

  dev -> nonce_audience [label="sign (KB-JWT)"]
}
@enduml
```

An error will be rendered: Syntax Error for line diagraph J

When I remove the !include line, the digram is rendered correctly.

**Expected behavior**
Rendering of the image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
 - Dependency versions: 2.3.0

**Additional context**

**Comment by cre8** [comment]
I think the styling is not working for digraphs, I get the same error with:
```
@startuml
!include https://raw.githubusercontent.com/MikhailKravets/mkdocs_puml/master/themes/default/dark.puml

digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
@enduml
```
So is this just a missing rule in the styling files or is it impossible and we need to ignore puml diagrams including digraphs?

**Comment by MikhailKravets** [comment]
Hi @cre8, thanks for letting me know about that! The bug is in PlantUML itself. PlantUML returns error if you apply any theme for `digraph`. I'm afraid, it doesn't even work for official themes, for example,

```
@startuml
!theme blueprint

digraph J {

  subgraph cluster_pid_provider {
    style=filled
    color=lightblue
    label="PID Provider"
    pp [label="key-pp (pp_priv, pp_pub)"]
    user_data [label="eID data"]
  }

  subgraph cluster_wallet {
    style=filled
    color=lightgreen
    label="Wallet"
    nonce_audience [label="nonce, audience"]
    dev [label="key-device (device_pub, device_priv)"]
  }
  pp -> dev [label="sign (SD-JWT)"]
  pp -> user_data [label="sign (SD-JWT)"]

  dev -> nonce_audience [label="sign (KB-JWT)"]
}
@enduml
```

[Display on PlantUML server](https://www.plantuml.com/plantuml/uml/ZL9DQyCm3BtdLtWzjT3Kzq576RsiPL3Oe8SnWXEhYObZ6rjEAQF_VOwTbdKVC5yiFRqdFHcl73ABlfFPdL2Lz1n8WsZSFQMM7HUrmCQNte6jj49GkAXqHvz5sp0XjvRrW8vsBTULAqpeGZlc42p51ZfmbCE1UOcKCzikXdh6HMsPQSY6V6GP8SwNAG-Z1s5X12-CrRtWO0E5XEFm965v4582Zq2bfRPBAUe6I-aXOfAL89UJtTEQx4Rv91QC8MzZiOLJ7jAfCM64wETa27mvcxn7vh1bmHcogm12jm68XFElVeyisC9_EAqjWFfgTH-LoQJIgeA2UIuW1DVv4PwJ2pxwvD3Vh1Ho4KJJT0yRpSab3clEHlVnAVA76xaJjIBJbtM-sRycNkByV8hlp2pv2Dm_l2V1zl4YE6ShK3nyWKy=) 

will give the same error.

As a workaround, you could either disable the theming or use alternative diagrams if possible—these seem to be the only options for now. 😕

**Comment by cre8** [comment]
> Hi @cre8, thanks for letting me know about that! The bug is in PlantUML itself. PlantUML returns error if you apply any theme for `digraph`. I'm afraid, it doesn't even work for official themes, for example,
> 
> ```
> @startuml
> !theme blueprint
> 
> digraph J {
> 
>   subgraph cluster_pid_provider {
>     style=filled
>     color=lightblue
>     label="PID Provider"
>     pp [label="key-pp (pp_priv, pp_pub)"]
>     user_data [label="eID data"]
>   }
> 
>   subgraph cluster_wallet {
>     style=filled
>     color=lightgreen
>     label="Wallet"
>     nonce_audience [label="nonce, audience"]
>     dev [label="key-device (device_pub, device_priv)"]
>   }
>   pp -> dev [label="sign (SD-JWT)"]
>   pp -> user_data [label="sign (SD-JWT)"]
> 
>   dev -> nonce_audience [label="sign (KB-JWT)"]
> }
> @enduml
> ```
> 
> [Display on PlantUML server](https://www.plantuml.com/plantuml/uml/ZL9DQyCm3BtdLtWzjT3Kzq576RsiPL3Oe8SnWXEhYObZ6rjEAQF_VOwTbdKVC5yiFRqdFHcl73ABlfFPdL2Lz1n8WsZSFQMM7HUrmCQNte6jj49GkAXqHvz5sp0XjvRrW8vsBTULAqpeGZlc42p51ZfmbCE1UOcKCzikXdh6HMsPQSY6V6GP8SwNAG-Z1s5X12-CrRtWO0E5XEFm965v4582Zq2bfRPBAUe6I-aXOfAL89UJtTEQx4Rv91QC8MzZiOLJ7jAfCM64wETa27mvcxn7vh1bmHcogm12jm68XFElVeyisC9_EAqjWFfgTH-LoQJIgeA2UIuW1DVv4PwJ2pxwvD3Vh1Ho4KJJT0yRpSab3clEHlVnAVA76xaJjIBJbtM-sRycNkByV8hlp2pv2Dm_l2V1zl4YE6ShK3nyWKy=)
> 
> will give the same error.
> 
> As a workaround, you could either disable the theming or use alternative diagrams if possible—these seem to be the only options for now. 😕

Thank you for looking at it, where do I find the config to disable theming?

**Comment by MikhailKravets** [comment]
You can read about in [Setup Theming](https://mikhailkravets.github.io/mkdocs_puml/getting_started/setup/#theming) docs page. You need use this config

```yaml
plugins:
  - plantuml:
      theme:
        enabled: false
```

**Comment by cre8** [comment]
> You can read about in [Setup Theming](https://mikhailkravets.github.io/mkdocs_puml/getting_started/setup/#theming) docs page. You need use this config
> 
> ```yaml
> plugins:
>   - plantuml:
>       theme:
>         enabled: false
> ```

Thank you, it worked. Up to you if you want to close this issue or leave it open until e.g. there is an update that will exclude uml diagrams that are not compatible with themes

**Comment by MikhailKravets** [comment]
I'll close this one. If you don't mind I'm going to raise this issue in PlantUML repo
